[project]
name = "render-datadog-event-forwarder"
version = "0.1.0"
description = "A small forwarder for sending Render events to Datadog"
requires-python = ">=3.10"
dependencies = [
    "datadog-api-client>=2.40.0",
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
    "standardwebhooks>=1.0.0",
]
